import os
import json
import googleapiclient.discovery
from datetime import datetime, timezone

api_key = os.environ["YOUTUBE_API_KEY"]
api_service_name = "youtube"
api_version = "v3"

CHANNELS = [
    "@gdcolon",
    "@andgo122",
    "@robtopgames",
    "@itszedargd",
    "@itzbrangd",
    "@zedardash",
    "@guitarherostyles",
    "@speedroute",
    "@stivenelvro",
    "@nexusgd10",
    "@glowstgd",
    "@habaneroagd",
    "@partitionsion",
    "@kaiguygd",
    "@chiefbrioso",
    "@mulpan",
    "@galluxi",
    "@xtrapnation",
    "@dashzedar",
    "@ciroxp",
    "@hbargd",
    "@hbargdclips",
    "@bitesterxbeast",
    "@lemoncak3",
    "@beanable",
    "@ericvanwilderman",
    "@dorami",
    "@mikhagd",
    "@itzsquidygd",
    "@titanchannel",
    "@kingsammelot",
    "@dasher...",
    "@Нелис",
    "@vortrox",
    "@deluxe12",
    "@imfernandouwu",
    "@decody",
    "@accretiongd",
    "@neiro1999",
    "@zoink",
    "@junipergd",
    "@maffaka",
    "@dolphygeometrydash",
    "@2.2",
    "@srguillester",
    "@moldygd",
    "@simonisbestgd",
    "@leneuinst",
    "@rockyjones",
    "@mistertopi",
    "@staggy_01",
    "@spu7nix",
    "@viprin",
    "@doggiedasher",
    "@bycraftxx",
    "@crazybogdashgames",
    "@worldgameimpossiblechallenges",
    "@soulstrkgd",
    "@xcreatorgoal",
    "@sdslayer100",
    "@sikky",
    "@npesta",
    "@riottt",
    "@aerovp",
    "@mrhappyjunior",
    "@toshdeluxe",
    "@knobbelboy",
    "@geck",
    "@very_big_head8845",
    "@michigun", # /\/\/\
    "@dsanimations",
    "@peterbrayhamgd",
    "@stacksoriginals",
    "@jhostyn25",
    "@tridegd",
    "@letsplaygeometrydash",
    "@fnm04",
    "@flubgeometrydash",
    "@hapypace",
    "@waboo",
    "@krmal",
    "@kriszgd",
    "@icedcave",
    "@aeonair",
    "@sunixl",
    "@rektorgd",
    "@wulzy",
    "@musicsoundsgd",
    "@sirkaelgd",
    "@relz",
    "@liaxlogagd",
    "@boffisgd",
    "@how-d",
    "@voxicat",
    "@razing717",
    "@nk7338",
    "@matmart",
    "@vortroxtwo",
    "@aliasgd",
    "@trickgmd",
    "@stalliongd",
    "@squishyman67",
    "@cursed6125",
    "@freshlakewater",
    "@thehypno1208",
    "@chriscredible",
    "@jonathangd",
    "@zobrosgd",
    "@lands1ide",
    "@secretwaygd",
    "@mindcap.",
    "@swagroute0",
    "@justagdplayer",
    "@adyagd",
    "@technicaljl",
    "@kingsammelive",
    "@vernamgd",
    "@vernamica",
    "@italianapkdownloader",
    "@selpix",
    "@cobgd",
    "@coolpizzamanstuff",
    "@vix50x",
    "@dailydosegd",
    "@samifyingvods",
    "@samifying",
    "@pressstartmonumental",
    "@stivenelvroplus",
    "@stivenelvroclips",
    "@dashtimegd",
    "@squidy",
    "@kaiguyskickback",
    "@baby__bellaaz",
    "@peterbrayhamyt",
    "@tutorialismic",
    "@mrlufegamertm",
    "@reemiigd",
    "@dima_gd_2",
    "@bli_gd",
    "@lopsidedchickengd",
    "@andromeda7674",
    "@tcd_media",
    "@advyshorts",
    "@algo.00",
    "@retromangd",
    "@adaf3003",
    "@checkyyoutubechannel",
    "@kirbygamer99",
    "@tespañol",
    "@enc0dy",
    "@trusta",
    "@guitargameplays",
    "@itzbranclips",
    "@purelsecret",
    "@gd_sayori",
    "@lukikkkk",
    "@coopermitcchell",
    "@gdskycyan",
    "@fenix_channel",
    "@3000dan",
    "@gs_gd",
    "@eiriley",
    "@whatgamerwha",
    "@1ncrediblebacon",
    "@etzergd",
    "@lemonsgd",
    "@wpopoff6461",
    "@iivangd",
    "@vit124",
    "@jamattack",
    "@norcdachilda",
    "@diamondgd",
    "@colours.gaming",
    "@smiffy777",
    "@danzmen9965",
    "@erender",
    "@ufokinwotm8gd",
    "@flaaroni",
    "@clayfuzzy",
    "@ycreatorgoal",
    "@raevezz_",
    "@xanii",
    "@gdsemicolon",
    "@serpongedash",
    "@zeronium",
    "@gmdblue",
    "@tubular9",
    "@stormfly",
    "@culuc",
    "@absolllute",
    "@rykiion",
    "@jeyzor",
    "@davjt",
    "@geoblitzy",
    "@redhuseey",
    "@paqoe",
    "@xtinctlol",
    "@blueskii",
    "@mathgeniusgd",
    "@onealphahelix",
    "@letim",
    "@wavix",
    "@xnyyct",
    "@fakedenni",
    "@leify1337",
    "@lordvadercraft",
    "@niftylololol",
    "@zymnitegd",
    "@geometrydashbrainrot",
    "@n1ckxd",
    "@bigthunder556",
    "@mrspaghettigd",
    "@audieo",
    "@paxlgd",
    "@vinnycha123",
    "@scharksatire",
    "@schark27",
    "@onilink",
    "@xtra8nuggies"
    "@tatox3_",
    "@nimpop",
    "@boldstep_gd",
    "@whizkid0521",
    "@conixgmd",
    "@mightyminors",
    "@gdcreatorschool",
    "@waterflamemusic",
    "@androxmagd",
    "@luqualizer",
    "@cdmusicyt",
    "@larriusdarius",
    "@maxdash3075",
    "@lastprismalex",
    "@bgram",
    "@itsmegeogd",
    "@smangogd",
    "@zallitz",
    "@leygd",
    "@diamondsplash",
    "@wooshi999",
    "@manix648",
    "@lation",
    "@stcubing",
    "@azureturk",
    "@woogi1411",
    "@septagon7",
    "@zerosr",
    "@arshadow",
    "@watchpiggy2",
    "@incidius",
    "@worsethanaeonairwastaken",
    "@juliannn999",
    "@robtopstreams",
    "@norkbork",
    "@hemagd",
    "@auskgd",
    "@swiborg",
    "@lmanubis",
    "@sh4rkygd",
    "@imhercs",
    "@gdalkali",
    "@xempir",
    "@personhuman42",
    "@anglified",
    "@klaux",
    "@electrifyxd",
    "@galaxydashgd",
    "@taiago_",
    "@lazerblitz101",
    "@cvolton",
    "@nothingisscary",
    "@yossariangd",
    "@kawaqii",
    "@gdgroundflower",
    "@lispdigital",
    "@wherwin",
    "@darwingd",
    "@cherry_team_gd",
    "@demishio5434",
    "@vee26.",
    "@notpara",
    "@polterghast12",
    "@realtophtalks",
    "@matttacc",
    "@rispgd",
    "@ant_gam3r",
    "@pigchefer",
    "@venomouscosmo",
    "@vitessers",
    "@the_zof",
    "@xendlevel",
    "@neigefeu__",
    "@troypm",
    "@ninjadangd",
    "@deathcorridor",
    "@thnnder",
    "@nikrodox",
    "@lazorsgd",
    "@alimicious",
    "@potatobrother1933",
    "@dice88",
    "@watchpiggy",
    "@lfritz",
    "@mohammedjakalemalabdulaantigd",
    "@dki8i_gd",
    "@batyagd1",
    "@andreya6",
    "@nicktria_",
    "@mrdasher69",
    "@galposaco",
    "@alexpain24",
    "@skewer56",
    "@clementdavgd",
    "@cloudgdyt",
    "@pimtogd",
    "@najungi",
    "@itzapexgd",
    "@iceemickey",
    "@stevenvrogd",
    "@랑께님",
    "@soyelcuberdegd",
    "@dave400ph",
    "@miniproxy04",
    "@luzoglive",
    "@pixeldropppgd",
    "@appsgd",
    "@twisted51",
    "@jenkshouse",
]

def main():
    youtube = googleapiclient.discovery.build(api_service_name, api_version, developerKey=api_key)
    
    output_data = {
        "lastUpdated": None,
        "Channels": {

        }
    }
    
    for channel in CHANNELS:
        request = youtube.channels().list(
            part="snippet,contentDetails,statistics",
            forHandle=channel
        )
        response = request.execute()
        try:
            sub_count = response['items'][0]['statistics']['subscriberCount']
            display_name = response['items'][0]['snippet']['title']
            output_data["Channels"][display_name] = [
                    sub_count,
                    channel
                ]
        except:
            print(f"{channel} was a problem...")
    
    timestamp = datetime.now(timezone.utc).timestamp()
    output_data["lastUpdated"] = timestamp

    os.makedirs("sub_stats_archive", exist_ok=True)

    print(output_data)

    with open("stats.json", "w") as f:
        json.dump(output_data, f, indent=2)
    with open(f"sub_stats_archive/{timestamp}.json", "w") as f:
        json.dump(output_data, f, indent=2)
    print("Updates written successfully to stats.json!")

if __name__ == "__main__":
    main()
